systems:
  - id: apanasenko.pro
    name: Будинок
    airtableId: appkDDXBH7aan0pzk
  # - id: mobble
  #   name: Inhout Mobble
  #   airtableId: app25JFkKVKKEt5io
  # - id: swift
  #   name: WikiHouse Swift
  #   airtableId: appGlzQcCZpDNRFsE
  # - id: holz100
  #   name: HOLZ100
  #   airtableId: appzG3plVRqgH6c5f
